@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NTYxODAzMzl9.lOZ3-eOx_Q9qxGJrec1trM_gDRhqIK8Z19Qf6_cW9pM
### Comments Create 

POST http://localhost:3000/comments.json
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "post_id": 2,
  "user_id": 2,
  "comment": "purrrrr"
}

### Comments Destroy

DELETE http://localhost:3000/comments/4.json
Authorization: Bearer {{jwt}}