### User Show

GET http://localhost:3000/users/4.json


### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Test name 3",
  "username": "username 3",
  "email": "test3@test.com",
  "password": "password",
  "password_confirmation": "password",
  "profile_pic": "pic.img",
  "sun": "sun3",
  "moon":"moon3",
  "rising":"rising3"
}

### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "password"
}